### ISSUE TITLE
background color not working

### ISSUE THREAD

**Issue by sfalihi** [irohitb/react-native-smart-statusbar#3]
hello 
i found two error in your last publish version 
1) DeviceInfo.hasNotch is async and return a promise so must change to DeviceInfo.hasNotchSync

2) background color for non notch devices not working because it has not any height so set the height in the second condition like this : 
```
else if (!DeviceInfo.hasNotchSync()) {
			return (
				<View
					style={{
						height: navbarHeight, //this line must be set
						backgroundColor: backgroundColor,
						width: Dimensions.get('window').width,
					}}
				>
					<StatusBar {...rest} translucent hidden={this.props.statusBarHiddenForNonNotch} />
				</View>
			)
		}
```

**Comment by irohitb** [comment]
Hey @sfalihi 
Investigating. I will push an update within the next 24 hours. 
Can you meanwhile share which platform are you using?

**Comment by sfalihi** [comment]
i test this in my galaxy note 4 device (android 6 non notch) and after changing these issues it worked

**Comment by sfalihi** [comment]
i think the last time that you fixed the bug the issue was not the statusbar height but it was  DeviceInfo.hasNotch!!!
so turn back the statusbarheight and just change DeviceInfo.hasNotch to DeviceInfo.hasNotchSync
and it will be fine.

**Comment by irohitb** [comment]
I think I forgot to try it out on Android the last time I pushed. I see the bug there, I will fix it first thing in the morning. 

Thanks for pointing it out and investigating :)

**Comment by sfalihi** [comment]
thank you for your amazing library

**Comment by irohitb** [comment]
@sfalihi Updated the package see if it works now? The problem with your code is that we can't give height in case of iOS because then there would be height for Navbar and height for view.
